### ISSUE TITLE
Error with connection.revoke_token

### ISSUE THREAD

**Issue by denny99** [figo-connect/node-figo#14]
When trying to revoke the refresh token with **connection.revoke_token(refresh_token, function (err, result) {})** the program stops with the following error

> c:\Users\Denny\WebstormProjects\localvoucher\node_modules\figo\lib\figo.js:238
>       callback(error, result);
>       ^
> 
> TypeError: callback is not a function
>     at c:\Users\Denny\WebstormProjects\localvoucher\node_modules\figo\lib\figo.js:238:7
>     at IncomingMessage.<anonymous> (c:\Users\Denny\WebstormProjects\localvoucher\node_modules\figo\lib\figo.js:128:9)
>     at emitNone (events.js:85:20)
>     at IncomingMessage.emit (events.js:179:7)
>     at endReadableNT (_stream_readable.js:906:12)
>     at nextTickCallbackWith2Args (node.js:475:9)
>     at process._tickDomainCallback (node.js:430:17)

The function revoke_token calls **this.query_api(/auth/revoke? + querystring.stringify(options), callback);** but query_api requires 3 parameters.

Used version: 1.3.3

**Comment by mfilenko** [comment]
Hey @denny99,

Thanks for reporting and sorry for that bug! It was fixed in the latest build. Please, update your copy of SDK.

Best,
Max
