### ISSUE TITLE
Unsupported Grant Type

### ISSUE THREAD

**Issue by cspeer** [figo-connect/node-figo#17]
Hi there,

I was trying to use the node api with your [demo credentials](http://docs.figo.io/#demo-access) but I'm getting this error:

```
{ Error
       at new FigoError (/Users/cspeer/Development/htdocs/jarvizz/node_modules/figo/lib/errors.js:13:17)
       at IncomingMessage.<anonymous> (/Users/cspeer/Development/htdocs/jarvizz/node_modules/figo/lib/figo.js:107:23)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:926:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickDomainCallback (internal/process/next_tick.js:122:9)
     name: 'FigoError',
     error:
      { code: 30400,
        group: null,
        name: 'HTTPClientError',
        message: 'unsupported_grant_type',
        data: {},
        description: 'Unsupported grant type.' },
     error_description: undefined,
     stack: ...
```

I then proceeded to give it another shot with actual user credentials (mine), same result.
I'm running figo 1.4.0.

The code is super simple:
```javascript
var figo = require('figo');
var c = new figo.Connection('CaESKmC8MAhNpDe5rvmWnSkRE_7pkkVIIgMwclgzGcQY', 'STdzfv0GXtEj_bwYn7AgCVszN1kKq5BdgEIKOM_fzybQ');
c.credential_login('demo@figo.me', 'demo1234', null, null, null, null, function() { console.log(arguments); });
```
Cheers,
Chris

**Comment by cspeer** [comment]
Seemingly not an issue with this node module:
```
curl -X POST \
-H 'Authorization: Basic Q2FFU0ttQzhNQWhOcERlNXJ2bVduU2tSRV83cGtrVklJZ013Y2xnekdjUVk6U1RkemZ2MEdYdEVqX2J3WW43QWdDVnN6TjFrS3E1QmRnRUlLT01fZnp5YlE=' \
-d 'grant_type=password&username=demo@figo.me&password=demo1234' \
https://api.figo.me/auth/token
```

So how can `grant_type` be invalid when the docs that that `password` [is accurate](http://docs.figo.io/#credential-login)?

**Comment by steinke** [comment]
Hey Chris
the call is correct however it not working with the demo users. We need to state this in the API documentation, so our fault. 
The demo credentials and user are a bit special. We created an access token for this user already that is valid indefinitely therefore you don't need to authenticate it again. 
For testing purpose you can use the access token directly provided in the docs and use it then as your Bearer token.
Once you have your own client credentials and create a new user the call and sdk work the way you tried it. 
Sorry for the confusion, we will update the documentation with some advice text soon
