### ISSUE TITLE
import in Meteor app doesn't work

### ISSUE THREAD

**Issue by mina1604** [figo-connect/node-figo#37]
I tried to require the figo node-sdk in our Meteor App. However, on start up of the app I always get this error and the whole app crashes. 

![image](https://cloud.githubusercontent.com/assets/5646578/25887481/a52feb64-3562-11e7-913b-7cd1f078813a.png)

**Comment by berend** [comment]
Do you have a stripped down example that reproduces the errors? I did this little example in plain node, that runs without any issues or require errors

```
var figo = require('figo');

var access_token = 'ASHWLIkouP2O6_bgA2wWReRhletgWKHYjLqDaqb0LFfamim9RjexTo22ujRIP_cjLiRiSyQXyt2kM1eXU2XLFZQ0Hro15HikJQT_eNeT_9XQ';
var session = new figo.Session(access_token);

session.get_accounts(function(error, accounts) {
  if (error) {
    console.error(error);
  } else {
    accounts.forEach(function(account) {
      console.log(account.account_number);
    });
  }
});
```

**Comment by berend** [comment]
Also, did you follow [these instructions](https://guide.meteor.com/using-npm-packages.html#installing-npm)?

**Comment by mina1604** [comment]
yes I already did. works now, thx anyway

**Comment by berend** [comment]
No problem. Are you able to share what was wrong? Maybe others will find that helpful.
