### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by xlarsx** [figo-connect/node-figo#5]
Good afternoon,
Trying to replicate the same test that ( https://travis-ci.org/figo-connect/node-figo/jobs/30104648 ) with the code at ( 0e7e306aa1540571c3f5c49af4e8f339d74b2f8f ) but I get 4 failing tests

1) should list all accounts
2) should list all transactions
3) should retrieve account A1.1
4) should allow management of a payment

Am I missing something? Thank you!

**Comment by mfilenko** [comment]
Hey @xlarsx,

What exceptions have been caught?
